### ISSUE TITLE
Discount % to be removed when manually discount amount is entered

### ISSUE THREAD

**Issue by Pappustore** [oitcode/Cbswei#1]
Discount % to be removed when manually discount amount is entered.

Please do the needful.

**Comment by oitcode** [comment]
Issue fixed.

Now user has to select between a manual discount or system calculated discount.

@Pappustore Please retest.

**Comment by oitcode** [comment]
Closing the issue now as fixed.

**Comment by oitcode** [comment]
Reopening: User can edit when discount is selected as % instead of manual. In this case user should not be able to edit.
